### PR TITLE
Fix for the critical issue of toast doing nothing

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by geo242** [comment]
@rajeshwarpatlolla Please merge this in and release it. Thanks!

**Comment by rajeshwarpatlolla** [comment]
Thanks for your PR.

**Comment by rajeshwarpatlolla** [comment]
I don't see anything in the UI after merging this PR. There is no text at all. Could you please cross check this issue and make a PR?
This is happening if i use the minified file. If i source the source files, then there is no animation and i can see the text.

screen shot 2016-07-12 at 3 04 10 pm

**Comment by ghost** [comment]
Hi rajeshwarpatlolla,

This shows the only change that needed to be made: https://github.com/rajeshwarpatlolla/ionic-toast/pull/19/commits/5ce924c79314c0cfc28b92ab1d2500f9ea58729e

I only meant to pull request the first two commits I made.  The other commits about adding the animations really changes things up internally (hence the bugs), and also it doesn't work for a toast in the middle, which would be a breaking change.  For that reason, should probably rollback to just those bugfix commits, and leave the animation ones till later.

Does github automatically try to pull request  later commits I have made?

**Pull request merged**
